# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Keystone Hugo Theme"
license = "MIT"
licenselink = "https://github.com/shishir-srivastava/keystone-hugo-theme/blob/master/LICENSE"
description = "The Keystone theme for Hugo is focused on content. It's a minimal theme, with SEO practices built in."
homepage = "https://github.com/shishir-srivastava/keystone-hugo-theme"
tags = [
  "blog",
  "minimal",
  "responsive",
  "AMP",
  "html5",
  "SEO"
]
features = []
min_version = "0.41"

[author]
  name = "Shishir Srivastava"
  homepage = "https://shishir.dev"

